name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build and Lint
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
